:revnumber: {docVersion}
:toclevels: 3

= [red]#Jenkins#
{docDate}

== Introduction
What is Jenkins

Jenkins is a *butler* and is this case that is the best word you can find for this machine which really runs all your
to do but not perse happy to do things :-)

== Install
* Download

== Run
.How to run
[source, shell]
----
$ java -jar jenkins.war
----

== Do
.Getting started
* Manage Jenkins
* Add Git plugin
* Set Maven
** set Maven home to /usr/share/maven (or where your Maven is)

.Add job
* New item
* New Maven project
* Git
** Set Version control to *Git*
** Set url in the git settings
* Maven
** Set goals to clean install
** Empty also works

== Fine tuning
We will add some nice plugins in this section to get you acquintainted with our friend Jenkins

.Add green balls plugin
* Target of this plugin is to make the balls green instead of blue
* Manage jenkins
* Manage plugins
* Add Green balls plugin

.Job configuration history plugin
* Target of this plugin is to enable a kind of rollback possibility when your changes fail the jenkins job

.Monitoring plugin
* Target: to get insight of Jenkins server (based on the populair Java Melody framework)


.Build pipeline plugin
* Target: to show you the flow of your builds when (mis)using Jenkins as a deploy server

TIP: http://www.praqma.com/stories/top-jenkins-plugins/


