:revnumber: {docVersion}
:toclevels: 3

= [red]#JPA OneToMany ManyToOne ManyToMany #
{docDate}

== Introductie

During this part of the training we will instruct using JPA
.OneToMany 
.ManyToOne 
.ManyToMany

== OneToOne

Suppose an Employee always has a single address and we have to model it in jpa

So we create the entity Addresss

[source, java]
----
package nl.programit.people.domain;
... imports omitted

@Entity
public class Address {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	private String street;
	private int number;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public int getNumber() {
		return number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

}

----

Example code

[source, java]
----
@Entity
public class Employee {

  @Id
  private long id;


  // fails with the exception that JPA does not know what type of column to create for Address? Clear??
  private Address address;
}
----

Fix the problem above with the *@OneToOne* annotation so JPA knows that it has to make a mapping to another table called a *relationship* / *foreign key*

[source, java]
----
@Entity
public class Employee {

  @Id
  private long id;


  @OneToOne
  private Address address;
}
----
Using the least work principe that is all we have to do to create the relationship.
.Under the hood JPA does the following work for us:
* it creates the table *Address*
* it creates an *address_id* column in the table Person

Now we have create a so called *unidirectional relationship* which means we can only traverse from the Person to the Address.
The address table / entity does not have any clue to which person it belongs!!!

== Bidirectional
Suppose we want to tell JPA also to wire the direction from Address to Person
Than we have to add this to the JPA Address entity

[source, java]
----
  // fetch = do we get all addressen when fetching a Person or do we fetch them when we "dive" into them ...
  /// mappedBy = the other / owning side his property (in this case address since that is the owning side of Person)
 @OneToOne(fetch=FetchType.LAZY, mappedBy="address")
  private Person person;

  // add getters and setters
----

Question: what happens to the tables in the people app?




Answer ... after a minute of discussing? 
Nothing ... why ? :-)

Since if jpa has an adress entity he can found the person by finding a person with an adress_id which is the samen as the id of this address instance.

image

== @OneToMany

=== Unidirectional

Suppose a person has many phones but a phone belongs to one person.

We than use the *@OneToMany* annotation

[source, java]
----
@OneToMany
	private List<Phone> phones;
----

JPA then creates a person_hobbies table? Why ?

Since the entity Hobby does not know that he is even linked to a Person hence JPA creates a so called *link table*
(Dutch: koppel tabel)

=== Bidirectional
Suppose we want to be able to get the person which own the phone

Add the mappedBy property to the @OneToMany annotation on the owning side

The mappedBy is ALWAYS the type of the List we are dealing with. Hence in this case it is the Phone class - which has the @ManyToOne - annotation.
Just pick the name of the variable and you are done ... for now :-)

[source, java]
----
@OneToMany(mappedBy="person") // person is the private Person instance var in the phone class
	private List<Phone> phones;
----

.Add the @ManyToOne annotation to the belonging side
[source, java]
----
@ManyToOne
	private Person person;
----

== @ManyToMany

=== Unidirectional

Suppose a person has many hobbies and a hobby can belong to multiple persons.

.Add this to the person class
[source, java]
----
@ManyToMany(cascade=CascadeType.ALL)
	private List<Hobby> fietsen = new ArrayList<>();----


=== Bidirectional

Suppose want to see al people who like *running*

.Add the following to the Person class (mappedBy)
[source, java]
----
@ManyToMany(mappedBy="people", cascade=CascadeType.ALL)
	private List<Hobby> hobbies = new ArrayList<>();
----

.Add the following to the Hobby class
[source, java]
----
@ManyToMany(cascade=CascadeType.ALL)
	private List<Person> people = new ArrayList<>();
----

TIP: Never use a mappedBy on both sides of the relationship. Simply only on the *owning* side

TIP: Be aware for the following
* using a getter to get the List of Hobbies out of person and than adding an item to the List will eventually fail.
Question: is the List when I am getting it a JPA object?

Solution: create a getter and create an addHobby to the Person class



== What is that Cascade thing?

* When a person is deleted what happens to the hobby?
** The Cascading defines what should happen to the underlying properties of an entity
** In fact we have to tell something about assocations and specially regarding aggregations and compositions
* I think it is for later for now :-)


== DIY
.Do it yourself

Just implement the above changes to your people project.

And be aware that you understand what you are doing. 
The upcoming week (wednesday, friday ...) we will implmement this for the Liebregts case)



