:revnumber: {docVersion}
:toclevels: 3

= [red]#Maven#
{revnumber}, 21 mei 2016

== Introductie
Hieronder een samenvatting van de punten die we deze week behandeld hebben. Ik maak een soort van highlights document
met daarin de onderwerpen die je eigenlijk nu zou moeten weten.

== Afkortingen en definities

* Build: het maken van een binair bestand voor de klant van de sourcecode
* Lokale maven repository: al je binaire bestanden. staan in je homedir (bijv. C:/Users/arjan) onder .m2/repository
		(Dus in C:/users/arjan/.m2/repository)
* pom.xml: de _startfile_ van Maven. Staat voor Project Object Model maar dat mag je weer vergeten.

== Wat is Maven
Maven is een project-management en build tool.
Met Maven maak je een build met

Maven heeft diverse goals (zoals clean, package en install)
hieronder een korte beschrijving

== Basis van Maven
Maven is gebaseerd op de veelbesproken *pom.xml*

De pom.xml is een XML file met daarin een beschrijving van het project en de instellingen van de afhandkelijkheden en dergelijke

=== POM
.Highlights van de POM
* groupId: bevat eigenlijk de packagename waarin je je project gaat zetten
* artifactId: bevat eigenlijk de jar die je gaat maken of eigenlijk de applicatienaam zelf
* version: de versie die je gaat maken (iets als 0.1.0-SNAPSHOT)
* dependencies: bevat meerdere dependency tags
* dependency: bevat een beschrijving van een *library* waar jouw project *afhankelijk* van is
** groupId: groupId van het artifact waar je afhankelijk van bent
** artifactId: zie boven

=== NB
* Tijdens het maken van een *build* *MOET* Maven een pom.xml kunnen vinden in DE HUIDIGE DIRECTORY
* Maven vindt de *dependencies* in de Maven central repo. Een grote bittenbak op internet met allerlei jars en zo


== Het maken van een build
clean: maakt je target directory leeg. Je verwijdert eigenlijk de binaire bestanden 
compile: compiled je sources naar classes maar doet daar verder nog niets mee
package: voert *compile* uit en maakt daarna een jar van je classes
install: voert *package* uit en copieert (install) dan je jar in je locale maven repository

Je ziet dat maven dus een soort van lifecycle heeft.

zie image:
rloman plaatje maven hier.

.Maak een jar file
[source, xml]
----
$ mvn clean package
----

.Maak een jar file en copy dit in je locale maven repo
[source, xml]
----
$ mvn clean install
----

== Starten van een project
Meerdere mogelijkheden.
* Uitchecken via Github (zie onder)
* Runnen van een create script
* Maken via de Spring boot starter site (zie onder)







