:revnumber: {docVersion}
:toclevels: 3

= [red]#Mockito#
{docDate}

== Introduction
Mockito is a mocking framework that tastes really good. It lets you write beautiful tests with a clean & simple API. Mockito doesn’t give you hangover because the tests are very readable and they produce clean verification errors. Read more about features & motivations


== Dependencies
.For SpringBoot
[source, xml]
----
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-test</artifactId>	
	<scope>test</scope>
</dependency>
----


== Using it
Suppose we want to test the PersonService it's save method

.PersonService (in src/main/java)
[source, java, options="nowrap"]
----
Service
@Transactional

package nl.programit.people.persistence;

// imports omitted
public class PersonService {
	
	private static final Logger LOGGER = LoggerFactory.getLogger(PersonService.class);
	
	@Autowired
	private PersonRepository personRepository;
	
	public Person save(Person person) {
		
		
		/*  aanroep van het door Mockito gemaakte contract (normaliter zet je dat natuurlijk hier
		niet in de code */
		Person result = this.personRepository.save(person);	
		
		return result;
	}
}
----

.The problem
The problem is that during JUnit testing the *personRepository* in the PersonService is a null pointer.
We could wire the entire application up but than we are talking about integration testing.
To comply with the principle of Unittesting we *must* only test our unit - in this case the *save* method

So that is the problem.

The solution is to use *Mockito* to _mock_ the personRepository's save method by doing this

.PersonServiceTest (in src/test/java)
[source, java, options="nowrap"]
----
package nl.programit.people.persistence;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.runners.MockitoJUnitRunner;

import nl.programit.people.domain.Person;

@RunWith(MockitoJUnitRunner.class)
public class PersonServiceTest {

	private static final String JANSSEN = "Klaassen";
	private static final String HANS = "Jan";

	@InjectMocks
	private PersonService personService;

	@Mock
	private PersonRepository personRepository;

	@Test
	public void testSave() {
		// mocking part
		Person personMock = new Person();
		personMock.setId(1);
		personMock.setFirstName(HANS);
		personMock.setLastName(JANSSEN);

		Person personToBeSaved = new Person();
		personToBeSaved.setFirstName(HANS);
		personToBeSaved.setLastName(JANSSEN);

		// contract voor de aanroep naar de personRepository
  		// this is where Mockito kicks in!!!
		Mockito.when(personRepository.save(personToBeSaved)).thenReturn(personMock);

		// testing part
		Person personSaved = this.personService.save(personToBeSaved);

		Assert.assertEquals(1, personSaved.getId());
		Assert.assertEquals(JANSSEN, personSaved.getLastName());
		Assert.assertEquals(HANS, personSaved.getFirstName());
	}

}

----

== More reading
* http://mockito.org/



