:revnumber: {docVersion}
:toclevels: 3

= [red]#Springboot / JPA exercise#
{docDate}

== Introductie

During this exercise we will use the develop branch from the repo to add a jpa repo

== Clone this url to get started

First go to your _repo_ directory on your file system. (your personal git repo)

[source, shell]
----
	$ git clone https://github.com/rloman/springboot-people.git
----

==  Add some setup

=== Add dependency to spring jpa
[source, xml]
----
 		<dependency>
 			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
 			<artifactId>spring-boot-starter-test</artifactId>
 			<scope>test</scope>
 		</dependency>
----

=== Change Person class
.Add @Entity and id to Person class
[source, java, options="nowrap"]
---- 
@Entity
 public class Person implements Serializable {
 
 	private static final long serialVersionUID = 5801378338363587926L;

	// technical key
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

 	private String firstName;
 	private String lastName;
 
+	public long getId() {
+		return id;
+	}
+
+	public void setId(long id) {
+		this.id = id;
+	}
+
 	public String getFirstName() {
 		return firstName;
 	}
 	public String toString() {
 		return "Person [firstName=" + firstName + ", lastName=" + lastName + "]";
 	}
+
----

=== Add application.properties file
.Add application.properties
[source, properties, options="nowrap"]
---- 
 
 multipart.maxFileSize: 128MB
 multipart.maxRequestSize: 128MB

spring.datasource.url=jdbc:mysql://localhost:3306/people
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username=rloman
spring.datasource.password=bloemen

spring.jpa.database_platform=org.hibernate.dialect.MySQL5Dialect

#NOT IN PRODUCTION. NICE IN DEVELOPMENT!!! 
spring.jpa.hibernate.ddl-auto=update
----

== Add PersonService and PersonRepository

=== Add PersonRepository
[source, java]
----
package nl.programit.people.persistence;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Component;

import nl.programit.people.domain.Person;

@Component
public interface PersonRepository extends CrudRepository<Person, Long> { 
	
	Person findByFirstName(String firstName);
}

----
=== Add PersonService
[source,java]
----
package nl.programit.people.persistence;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@Transactional
public class PersonService {

}
----
== Add PersonRepository to PersonService
[source, java]
----
 package nl.programit.people.persistence;
 
import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Service;
 import org.springframework.transaction.annotation.Transactional;
 
import nl.programit.people.domain.Person;

 @Service
 @Transactional
 public class PersonService {
+	
+	@Autowired
+	private PersonRepository personRepository;
+	
+	public void save(Person person) {
+		
+		
+		this.personRepository.save(person);		
+
+	}
 
}
----

== Add findAll to PersonService and inject PersonService in PersonController

=== Add / change insert to PersonController
[source, java]
----
 package nl.programit.people.controller;
 
-import java.util.ArrayList;
-import java.util.List;
-
 import javax.servlet.http.HttpServletResponse;
 
+import org.springframework.beans.factory.annotation.Autowired;
 import org.springframework.stereotype.Controller;
 import org.springframework.web.bind.annotation.RequestMapping;
 import org.springframework.web.bind.annotation.RequestMethod;
 import org.springframework.web.bind.annotation.ResponseBody;
 
 import nl.programit.people.domain.Person;
+import nl.programit.people.persistence.PersonService;
 
 @Controller
 public class PersonController {
 
	@Autowired
	private PersonService personService;
 
 	@RequestMapping(value = "/list", method = RequestMethod.GET)
 	public @ResponseBody String list() {
		return this.personService.findAll().toString();
 	}

	@RequestMapping(value = "/insert", method = RequestMethod.POST)
	public void handleFileUpload(@RequestParam("name") String name,
			@RequestParam(required = false, value = "renderPresentationNotes") boolean renderPresentationNotes,
			@RequestParam("lastName") String lastName, HttpServletResponse response) {

		Person person = new Person();
		person.setFirstName(name);
		person.setLastName(lastName);
		
		this.personService.save(person);

	}
 }
----

=== Add findAll to PersonService
[source, java]
----
+	
+	public Iterable<Person> findAll() {
+		Iterable<Person> result = this.personRepository.findAll();
+		
+		return result;
+	}
 
 }

----
== Set correct userId and add mysql dep to pom.xml
=== Add mysql-connector dependency to pom.xml
[source, xml]
----
 		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
		</dependency>
 			<groupId>org.springframework.boot</groupId>
 			<artifactId>spring-boot-starter-data-jpa</artifactId>
 		</dependency>
----

=== Add / amend application.properties
[source, properties, options="nowrap"]
----

 multipart.maxFileSize: 128MB
 multipart.maxRequestSize: 128MB
 
spring.datasource.url=jdbc:mysql://localhost:3306/person
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=bloemen
spring.jpa.database_platform=org.hibernate.dialect.MySQL5Dialect
----


