:revnumber: {docVersion}
:toclevels: 3

= [red]#Summary week 2#
{docDate}

== Introductie
Hieronder een samenvatting van wat we in week 2 behandeld hebben


== MySQL
.How to start MySQL in Windows
* Add it as a service after installing Windows

== Testomgeving
.Hoe krijg ik een fixture ingericht
* Door bijvoorbeeld een file te maken met daarin key value paren voor geldige test gevallen
* Of je maakt een soort van Map in je code waarin je een key, value paar opneemt
* Je moet het niet te breed zien. Dit is een unittest en niet een complete *echte* test die een tester doet

== How to set the Java version in pom.xml ?
.Door dit op te nemen in jouw pom in de build sectie
[source, xml]
----
...
<build>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.5.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
...
----

== Jad installeren en aan de praat krijgen
* Download
* Install (extract)
* Add jad to your *system* path variable
* Go to dir where your .class file is
* jad <className>.class
** It rocks!

== Spring
.Annotations
* link: http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/
* link: https://dzone.com/refcardz/spring-annotations#
* link naar de spring source site
* Link tip van Hans (moet hem zelf nog gaan kijken)
** http://www.leanstacks.com/media.html 

== Dependencies toevoegen
* Hoe groot is de kans dat je _conflicterende_ belangen krijg?
** Normaliter heb je niet zo snel een conflict in dependencies
** Zo wel dan bevindt je je in de _dependency hell_
** Op te lossen door een goede repository manager (week 5)
** Maar das wel een _senior_ klusje

== MySQL
.Hoe moet ik inloggen
[source, shell]
----
$ example: mysql -u <username> -p
$ mysql -u rik -p
Enter password: 
example: use <database>
use hotel;
show tables;
select * from inventory;
----

== Unittesten
.Opzetten van Unittesten
* Voeg toe aan pom.xml
[source, xml]
----
<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
----


* Maak dir in jouw project _src/test/java_
* Voeg een class toe die eindigt op de naam _Test_
* Maak methodes die beginnen met _test_
* Annoteer die methode met @Test
* Run de test


.Voorbeeld
[source, java]
----
package eu.programit;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;


public class FibonTest {
	
	private Fibon fibon;
	
	// runs before EVERY test
	@Before
	public void setUp() {
		this.fibon = new Fibon();
	}
	
	// testcase
	@Test
	public void testFibon() {
		
		int test = fibon.fibon(5);
		
		Assert.assertEquals(5,  test);
		
	}

}

----
